[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hrenpack"
version = "3.1.5"
description = "Универсальная библиотека python для большинства задач | A universal python library for most tasks"
readme = "README.md"
authors = [
    {name = "MagIlyasDOMA", email = "magilyas.doma.09@list.ru"},
]
license = {text = "MIT"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Natural Language :: English",
    "Natural Language :: Russian",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Security :: Cryptography",
    "Topic :: Text Processing :: Markup",
    "Topic :: Text Processing :: Markup :: HTML",
]
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "chardet>=5.2.0",
    "charset-normalizer>=3.4.4",
    "requests>=2.32.5",
    "tqdm>=4.67.1, <=5.0.0",
    "bcrypt==5.0.0",
    "screeninfo>=0.8.1",
    "clipboard>=0.0.4",
    "psutil",
    "python-dotenv>=1.2.0",
    "python-gettext~=5.0",
    "pathlike-typing",
    "argparse-typing>=0.2.0",
    "tzlocal",
    "pytz",
    "typeguard",
    "undefined-python>=1.1.0",
]

[project.optional-dependencies]
image = [
    "Pillow>=3.3.0",
]
flask = [
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "flask-wtf>=1.2.2",
    "jinja2>=3.1.6",
    "markupsafe>=3.0.3",
]
filetype = [
    "filetype>=1.2.0",
    "puremagic~=1.30",
]
pyside6 = [
    "Pyside6>=6.8.2",
    "pyqtcli>=0.1.1",
]
django = [
    "Django>=5.2.9",
]
pygame = [
    "pygame>=2.6.1",
]
email = [
    "imapclient",
    "mail-parser==4.1.4"
]
all = [
    "Pillow>=3.3.0",
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "flask-wtf>=1.2.2",
    "jinja2>=3.1.6",
    "markupsafe>=3.0.3",
    "filetype>=1.2.0",
    "puremagic~=1.30",
    "Pyside6>=6.8.2",
    "pyqtcli>=0.1.1",
    "Django>=5.2.9",
    "pygame>=2.6.1",
    "imapclient",
]
full = [
    "Pillow>=3.3.0",
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "flask-wtf>=1.2.2",
    "jinja2>=3.1.6",
    "markupsafe>=3.0.3",
    "filetype>=1.2.0",
    "puremagic~=1.30",
    "Pyside6>=6.8.2",
    "pyqtcli>=0.1.1",
    "Django>=5.2.9",
    "pygame>=2.6.1",
    "imapclient",
]
dev_all = [
    "Pillow>=3.3.0",
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "flask-wtf>=1.2.2",
    "jinja2>=3.1.6",
    "markupsafe>=3.0.3",
    "filetype>=1.2.0",
    "puremagic~=1.30",
    "Pyside6>=6.8.2",
    "pyqtcli>=0.1.1",
    "Django>=5.2.9",
    "pygame>=2.6.1",
    "imapclient",
]
dev_full = [
    "Pillow>=3.3.0",
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "flask-wtf>=1.2.2",
    "jinja2>=3.1.6",
    "markupsafe>=3.0.3",
    "filetype>=1.2.0",
    "puremagic~=1.30",
    "Pyside6>=6.8.2",
    "pyqtcli>=0.1.1",
    "Django>=5.2.9",
    "pygame>=2.6.1",
    "imapclient",
]

[project.urls]
Source = "https://github.com/MagIlyasDOMA/hrenpack"
Documentation = "https://magilyasdoma.github.io/hrenpack/documentation.html"
Changelog = "https://github.com/MagIlyasDOMA/hrenpack/blob/main/CHANGELOG.md"

[tool.setuptools]
packages = {find = {}}
include-package-data = true

[dependency-groups]
dev = [
    "pylint>=4.0.5",
]
