[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hrenpack"
version = "3.0.0-beta.3"
description = "Универсальная библиотека python для большинства задач | A universal python library for most tasks"
readme = "README.md"
authors = [
    {name = "Маг Ильяс DOMA (MagIlyasDOMA)", email = "magilyas.doma.09@list.ru"},
]
license = {text = "MIT"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Natural Language :: English",
    "Natural Language :: Russian",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Security :: Cryptography",
    "Topic :: Text Processing :: Markup",
    "Topic :: Text Processing :: Markup :: HTML",
]
requires-python = ">=3.13"
dynamic = ["dependencies", "optional-dependencies"]

[project.urls]
Source = "https://github.com/MagIlyasDOMA/hrenpack"
Documentation = "https://magilyasdoma.github.io/hrenpack/documentation.html"
Changelog = "https://github.com/MagIlyasDOMA/hrenpack/blob/main/CHANGELOG.md"

[tool.setuptools]
packages = {find = {}}
include-package-data = true

[tool.setuptools.dynamic]
dependencies = {file = ["requirements/requirements.txt"]}

[tool.setuptools.dynamic.optional-dependencies]
image = {file = ["requirements/image_requirements.txt"]}
flask = {file = ["requirements/flask_requirements.txt"]}
filetype = {file = ["requirements/filetype_requirements.txt"]}
pyside6 = {file = ["requirements/pyside6_requirements.txt"]}
django = {file = ["requirements/django_requirements.txt"]}
pygame = {file = ["requirements/pygame_requirements.txt"]}
kivy = {file = ["requirements/kivy_requirements.txt"]}
dev = {file = ["requirements/dev_requirements.txt"]}
dev_base = {file = ["requirements/dev_requirements.txt"]}
dev_image = {file = [
    "requirements/dev_requirements.txt",
    "requirements/image_requirements.txt"
]}
dev_flask = {file = [
    "requirements/dev_requirements.txt",
    "requirements/flask_requirements.txt"
]}
dev_filetype = {file = [
    "requirements/dev_requirements.txt",
    "requirements/filetype_requirements.txt"
]}
dev_pyside6 = {file = [
    "requirements/dev_requirements.txt",
    "requirements/pyside6_requirements.txt"
]}
dev_django = {file = [
    "requirements/dev_requirements.txt",
    "requirements/django_requirements.txt"
]}
dev_pygame = {file = [
    "requirements/dev_requirements.txt",
    "requirements/pygame_requirements.txt"
]}
dev_kivy = {file = [
    "requirements/dev_requirements.txt",
    "requirements/kivy_requirements.txt"
]}
all = {file = [
    "requirements/image_requirements.txt",
    "requirements/flask_requirements.txt",
    "requirements/filetype_requirements.txt",
    "requirements/pyside6_requirements.txt",
    "requirements/django_requirements.txt",
    "requirements/pygame_requirements.txt",
    "requirements/kivy_requirements.txt"
]}
full = {file = [
    "requirements/image_requirements.txt",
    "requirements/flask_requirements.txt",
    "requirements/filetype_requirements.txt",
    "requirements/pyside6_requirements.txt",
    "requirements/django_requirements.txt",
    "requirements/pygame_requirements.txt",
    "requirements/kivy_requirements.txt"
]}
dev_all = {file = [
    "requirements/dev_requirements.txt",
    "requirements/image_requirements.txt",
    "requirements/flask_requirements.txt",
    "requirements/filetype_requirements.txt",
    "requirements/pyside6_requirements.txt",
    "requirements/django_requirements.txt",
    "requirements/pygame_requirements.txt",
    "requirements/kivy_requirements.txt"
]}
dev_full = {file = [
    "requirements/dev_requirements.txt",
    "requirements/image_requirements.txt",
    "requirements/flask_requirements.txt",
    "requirements/filetype_requirements.txt",
    "requirements/pyside6_requirements.txt",
    "requirements/django_requirements.txt",
    "requirements/pygame_requirements.txt",
    "requirements/kivy_requirements.txt"
]}
